services:
  web:
    image: nginx:latest
    container_name: web-php
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - php-network

  db:
    image: mysql:9.3
    container_name: db-php
    volumes:
        - /tmp/mysqldata:/var/lib/mysql
    ports:
      - "0.0.0.0:3306:3306"
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - php-network

#  cache:
#    container_name: cache-php
#    image: redis:latest

  app:
    build:
      dockerfile: ./php/Dockerfile
    container_name: app-php
    volumes:
      - ./app:/var/www/html
      - ./scripts:/opt
    restart: unless-stopped
    networks:
      - php-network

networks:
  php-network:
    driver: bridge